server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: portrally-core-api
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:port_rally}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  sql:
    init:
      mode: never

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}

  # kafka:
  #   bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    root: INFO
    org.springframework: INFO
    api: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
